// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: posts.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const checkNewPosts = `-- name: CheckNewPosts :one
SELECT EXISTS (
    SELECT 1 FROM posts
    JOIN feed_follows ON posts.feed_id = feed_follows.feed_id
    WHERE feed_follows.user_id = $1 
    AND posts.created_at > (SELECT created_at FROM posts WHERE posts.id = $2)
)
`

type CheckNewPostsParams struct {
	UserID uuid.UUID
	ID     uuid.UUID
}

func (q *Queries) CheckNewPosts(ctx context.Context, arg CheckNewPostsParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkNewPosts, arg.UserID, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createPost = `-- name: CreatePost :one
INSERT INTO posts (id, created_at, updated_at, title, description, published_at, url, feed_id) 
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, created_at, updated_at, title, description, published_at, url, feed_id
`

type CreatePostParams struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Title       string
	Description sql.NullString
	PublishedAt time.Time
	Url         string
	FeedID      uuid.UUID
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, createPost,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Title,
		arg.Description,
		arg.PublishedAt,
		arg.Url,
		arg.FeedID,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Description,
		&i.PublishedAt,
		&i.Url,
		&i.FeedID,
	)
	return i, err
}

const deleteOldPosts = `-- name: DeleteOldPosts :exec
DELETE FROM posts 
WHERE published_at < NOW() - INTERVAL '30 days'
`

func (q *Queries) DeleteOldPosts(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteOldPosts)
	return err
}

const getDiversePosts = `-- name: GetDiversePosts :many
WITH RankedPosts AS (
    SELECT 
        posts.id, posts.created_at, posts.updated_at, posts.title, posts.description, posts.published_at, posts.url, posts.feed_id, 
        feeds.name AS feed_name, 
        feeds.icon_url AS feed_icon,
        ROW_NUMBER() OVER (PARTITION BY posts.feed_id ORDER BY posts.published_at DESC) as rank
    FROM posts
    JOIN feeds ON posts.feed_id = feeds.id
)
SELECT id, created_at, updated_at, title, description, published_at, url, feed_id, feed_name, feed_icon, rank FROM RankedPosts 
WHERE rank <= 10 
ORDER BY published_at DESC 
LIMIT $1
`

type GetDiversePostsRow struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Title       string
	Description sql.NullString
	PublishedAt time.Time
	Url         string
	FeedID      uuid.UUID
	FeedName    string
	FeedIcon    string
	Rank        int64
}

func (q *Queries) GetDiversePosts(ctx context.Context, limit int32) ([]GetDiversePostsRow, error) {
	rows, err := q.db.QueryContext(ctx, getDiversePosts, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDiversePostsRow
	for rows.Next() {
		var i GetDiversePostsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.Description,
			&i.PublishedAt,
			&i.Url,
			&i.FeedID,
			&i.FeedName,
			&i.FeedIcon,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPostsForUser = `-- name: GetPostsForUser :many
SELECT 
    posts.id, posts.created_at, posts.updated_at, posts.title, posts.description, posts.published_at, posts.url, posts.feed_id, 
    feeds.name as feed_name, 
    feeds.icon_url as feed_icon
FROM posts
JOIN feeds ON posts.feed_id = feeds.id
JOIN feed_follows ON feed_follows.feed_id = feeds.id
WHERE feed_follows.user_id = $1
ORDER BY posts.published_at DESC
`

type GetPostsForUserRow struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Title       string
	Description sql.NullString
	PublishedAt time.Time
	Url         string
	FeedID      uuid.UUID
	FeedName    string
	FeedIcon    string
}

func (q *Queries) GetPostsForUser(ctx context.Context, userID uuid.UUID) ([]GetPostsForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getPostsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPostsForUserRow
	for rows.Next() {
		var i GetPostsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.Description,
			&i.PublishedAt,
			&i.Url,
			&i.FeedID,
			&i.FeedName,
			&i.FeedIcon,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPostsForUser = `-- name: SearchPostsForUser :many
SELECT 
    posts.id, posts.created_at, posts.updated_at, posts.title, posts.description, posts.published_at, posts.url, posts.feed_id, 
    feeds.name AS feed_name, 
    feeds.icon_url AS feed_icon
FROM posts
JOIN feeds ON posts.feed_id = feeds.id
JOIN feed_follows ON feed_follows.feed_id = feeds.id
WHERE feed_follows.user_id = $1 
  AND (posts.title ILIKE '%' || $2 || '%' OR posts.description ILIKE '%' || $2 || '%')
ORDER BY posts.published_at DESC
`

type SearchPostsForUserParams struct {
	UserID  uuid.UUID
	Column2 sql.NullString
}

type SearchPostsForUserRow struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Title       string
	Description sql.NullString
	PublishedAt time.Time
	Url         string
	FeedID      uuid.UUID
	FeedName    string
	FeedIcon    string
}

func (q *Queries) SearchPostsForUser(ctx context.Context, arg SearchPostsForUserParams) ([]SearchPostsForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, searchPostsForUser, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchPostsForUserRow
	for rows.Next() {
		var i SearchPostsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.Description,
			&i.PublishedAt,
			&i.Url,
			&i.FeedID,
			&i.FeedName,
			&i.FeedIcon,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
